### ISSUE TITLE
error in class Z2UI5_CL_APP_DEMO_70

### ISSUE THREAD

**Issue by choper725** [abap2UI5/demo-demos#14]
ERROR IN CLASS: Z2UI5_CL_APP_DEMO_70

!iv_selkz TYPE abap_boolean.

type abap_boolean unknowen

**Comment by oblomov-dev** [comment]
fixed with https://github.com/abap2UI5/demo-demos/commit/1ab901e9ab909fa2893db8a8e9b24ad93079367a

**Comment by choper725** [comment]
error is at

![image](https://github.com/abap2UI5/demo-demos/assets/129428114/de19fde0-112a-4e9b-bc6d-4be6e09554ab)

**Comment by choper725** [comment]
fixed in https://github.com/abap2UI5/demo-demos/pull/15/commits/e234cde57c59ac2851015cb2e76d19f5e0fc62bb
