### ISSUE TITLE
Demo Custom Control is not working 

### ISSUE THREAD

**Issue by nomssi** [abap2UI5/demo-demos#16]
Class Z2UI5_CL_APP_DEMO_37
I can load the custom control, but there is a JS error while trying to display it.
![image](https://github.com/abap2UI5/abap2UI5/assets/18452507/8a86f47c-6ad8-4822-807a-2d452e13a0d1)

**Comment by oblomov-dev** [comment]
Updates the demo https://github.com/abap2UI5/demo-demos/commit/301873fd665d715ab49821cba6aa14d2ce510b8c
Should work now.
