### ISSUE TITLE
DEMO 71

### ISSUE THREAD

**Issue by choper725** [abap2UI5/demo-demos#17]
HI @oblomov-dev 
there is an error getting lt_arg from the event.

![image](https://github.com/abap2UI5/demo-demos/assets/129428114/f781604a-804e-4c21-9b69-99bdbf4a605e)

not getting the value of ROW_ID in lt_arg, instead getting the value sent as a string
![image](https://github.com/abap2UI5/demo-demos/assets/129428114/f230bfe6-e75a-4c83-9da1-fe579e436d26)

**Comment by oblomov-dev** [comment]
thank you, fixed with https://github.com/abap2UI5/abap2UI5/pull/400

**Comment by choper725** [comment]
got another one there
![image](https://github.com/abap2UI5/demo-demos/assets/129428114/d7054b9a-a8ec-4c4a-aff7-cc2fc39da8d3)
